### ISSUE TITLE
Cannot access the render_component now.

### ISSUE THREAD

**Issue by arthurlee** [activescaffold/active_scaffold_demo#1]
Here is the error message in my computer:
E:\temp\rails\active_scaffold_demo>git submodule update
Initialized empty Git repository in E:/temp/rails/active_scaffold_demo/vendor/plugins/render_component/.git/
fatal: The remote end hung up unexpectedly
Clone of 'git://github.com/lackac/render_component.git' into submodule path 'vendor/plugins/render_component' failed

E:\temp\rails\active_scaffold_demo>

**Comment by yairgo** [comment]
Try to update to the newest version.  If that doesn't work delete the project and clone it again.  It was using a bad submodule.  Let me know if it works for you.

**Comment by arthurlee** [comment]
Thanks. It is ok now.

**Comment by yairgo** [comment]
No problem.  I don't know when the last time this was updated.  If you have any other issues or questions you can file another ticket and I'll try to respond as quickly as I can
